language: python

matrix:
  include:

    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

before_script: 
  - pip install docker-compose

script:
  - bash build.sh
  - docker pull $DOCKER_USERNAME/bmborrowdjango_web
  - docker tag bmborrowdjango_web $DOCKER_USERNAME/bmborrowdjango_web
  - docker push $DOCKER_USERNAME/bmborrowdjango_web 

  