language: python

matrix:
  include:

    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - docker-compose run web python  borrowDomain/manage.py makemigrations
  - docker-compose run web python  borrowDomain/manage.py migrate
  - bash build.sh
  - bash docker_push

  