language: python

matrix:
  include:

    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose  
stages:
  - unit test
  - deploy dockerhub
  
jobs:
  include:
  - stage: unit test
    script: bash build.sh
  - stage: deploy dockerhub
    script: 
     - docker pull $DOCKER_USERNAME/bmborrowdjango_web
     - docker tag bmborrowdjango_web $DOCKER_USERNAME/bmborrowdjango_web
     - docker push $DOCKER_USERNAME/bmborrowdjango_web 

before_install:
#Docker login
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

