language: python

matrix:
  include:
    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - bash build.sh
  - bash docker_push