language: python

matrix:
  include:

    - python: 3.5

virtualenv:
  system_site_packages: true

services:
  - docker

before_script: 
  - pip install docker-compose

script:
  - bash build.sh
  - bash docker_push

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t letzshake/bmborrowdjango_web .  
  - docker run -d --name bmborrowed -t letzshake/bmborrowdjango_web python ./borrowDomain/manage.py runserver 0.0.0.0:8000
  - sleep 15
  - docker run --name owasp --link bmborrowed -t owasp/zap2docker-weekly zap-full-scan.py -t http://bmborrowed:8000