version: '3'
services: 
  web:
    build: .
    command: python borrowDomain/manage.py runserver 0.0.0.0:8001
    volumes: 
      - .:/code
    ports: 
      - "8001:8001"
before install:
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

stages:
  - unit test
  - deploy dockerhub

jobs:
  include:
  - stage: unit test
   script: bash build.sh
  - stage: deploy dockerhub
  script: bash docker_push
