version: '3'
services: 
  web:
    build: .
    command: python borrowDomain/manage.py runserver 0.0.0.0:8001
    volumes: 
      - .:/code
    ports: 
      - "8001:8001"


stages:
  - unit test
  - deploy dockerhub

jobs:
  include:
  - stage: unit test
   script: bash build.sh
  - stage: deploy dockerhub
  script:
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
    - docker pull $DOCKER_USERNAME/bmborrowdjango_web
    - docker tag bmborrowdjango_web $DOCKER_USERNAME/bmborrowdjango_web
    - docker push $DOCKER_USERNAME/bmborrowdjango_web 

